name: Deploy Composer Library

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]  # OS. ubuntu-18.04 is also available.
        php: [ '7.4', '8.0' ] # PHP versions to check.
        include:
          - os: ubuntu-18.04
            php: 5.6
            tools: composer:v2.2
    name: Test in PHP ${{ matrix.php }} UnitTest
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.tools }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check PHP syntax
        run: composer lint

  assets:
    name: Check Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install NPM Packages
        run: npm install

      - name: Check JS & CSS syntax
        run: npm run lint

  release:
    name: Deploy GitHub Release
    needs: [ test, assets ]
    if: contains(github.ref, 'tags/')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Cleanup package.
        run: bash bin/clean.sh

      - name: Create Zip
        run: zip -r ${{ github.event.repository.name }}.zip ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release Block Library ${{ github.ref }}
          body: |
            Release Block Library version ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Release Zip
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
